name: Publicar PDF Compilado

on:
  push:
    branches:
      - main

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Compactar arquivos para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          # Envia o conteúdo da raiz do repositório
          path: '.'

      - name: Fazer Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
